### ISSUE TITLE
Concurrent skip list

### ISSUE THREAD

**Issue by ghost** [et4te/swim#1]
Hey, I just saw that you're using `SkipMap` in this project!

Since this is apparently one of the first uses of this data structure, I wonder if you have any feedback to share? For example, I would be interested if the skiplist delivers the desired performance, or if you hit any roadblocks with it.

**Comment by et4te** [comment]
Hey @ghost, apologies for the very delayed response. This repository was meant as an experiment to implement `SWIM` gossip and consensus protocols. The `SkipMap` worked quite well for the purposes I had at the time and I didn't run into any subsequent issues with it. In a future repository if I use `SkipMap` where there is production performance / other aspects to evaluate this would be better than with this prototypical codebase.
